### ISSUE TITLE
GitLab MR: undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bittner** [voxpupuli/modulesync#187] opened 2020-08-05 09:51 UTC
I'm running a `msync update --pr foo` command to create a MR on GitLab. The command fails in `modulesync`'s `pr` method:

```ruby
Syncing foo/bar-baz
Cloning repository fresh
Cloning from git@gitlab.example.com:foo/bar-baz.git
Creating new branch managed-configuration-update
Error while updating foo/bar-baz
/usr/local/bundle/gems/modulesync-1.3.0/lib/modulesync.rb:186:in `pr': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/modulesync-1.3.0/lib/modulesync.rb:137:in `manage_module'
	from /usr/local/bundle/gems/modulesync-1.3.0/lib/modulesync.rb:174:in `block in update'
	from /usr/local/bundle/gems/modulesync-1.3.0/lib/modulesync.rb:172:in `each'
	from /usr/local/bundle/gems/modulesync-1.3.0/lib/modulesync.rb:172:in `update'
	from /usr/local/bundle/gems/modulesync-1.3.0/lib/modulesync/cli.rb:142:in `update'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/modulesync-1.3.0/bin/msync:8:in `<top (required)>'
	from /usr/local/bundle/bin/msync:23:in `load'
	from /usr/local/bundle/bin/msync:23:in `<main>'
```
Related source: [lib/modulesync.rb, line 186](https://github.com/voxpupuli/modulesync/blob/1.3.0/lib/modulesync.rb#L186)

It looks like `module_options` is still unset [when used in the call to `pr`](https://github.com/voxpupuli/modulesync/blob/1.3.0/lib/modulesync.rb#L137) on line 137.

**Comment by ekohl** [comment] 2020-08-05 10:30
Isn't this a duplicate of https://github.com/voxpupuli/modulesync/issues/172?

**Comment by bittner** [comment] 2020-08-05 11:42
That very much looks like it is. So, this is a regression. We should write a test for the problem and [apply the old fix](https://github.com/voxpupuli/modulesync/pull/186/files) again.

**Comment by bittner** [comment] 2020-08-05 14:25
I see that this fix has just been recently merged into the main branch. Do you plan to release a new version with the fix soon?

**Comment by bittner** [comment] 2020-08-05 16:36
The fix doesn't resolve the problem for us. It looks like the `nil` is set explicitly in the parameter list. I'll investigate.

**Closed** 2020-08-11 20:39 UTC
Labels: bug
